name: Deploy Docker Container

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start Docker daemon (DinD)
        run: |
          sudo systemctl start docker

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image from GHCR
        run: docker pull ghcr.io/hafifrhn/practest-hafif-raihan:latest

      - name: Run Docker container
        run: |
          docker run -d --rm --name practest-hafif-raihan -p 8081:8080 ghcr.io/hafifrhn/practest-hafif-raihan:latest

      - name: List running containers
        run: docker ps

      - name: Test practest.html
        run: |
          sleep 5
          curl http://localhost:8081/practest.html
